// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DraggableController from "./draggable_controller"
application.register("draggable", DraggableController)

import DroppableController from "./droppable_controller"
application.register("droppable", DroppableController)

import CartController from "./cart_controller"
application.register("cart", CartController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)
