// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddWithAjaxController from "./add_with_ajax_controller.js"
application.register("add-with-ajax", AddWithAjaxController)
