services:
  db:
    image: postgres:14
    volumes:
      - ./tmp/db:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: password

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/dev
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      - db
    stdin_open: true
    tty: true
