FROM ruby:3.3.12-slim-trixie

RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libpq-dev \
    git \
    curl \
    libvips \
    postgresql-client && \
    curl -fsSL https://deb.nodesource.com/setup_24.x | bash - && \
    apt-get install -y nodejs

RUN npm install --global yarn

WORKDIR /app

COPY Gemfile ./
RUN bundle install

# Install JS dependencies 
# We add --ignore-engines just in case, but Node 18 fixes the primary error
COPY package.json yarn.lock ./
RUN yarn install --ignore-engines

# Copy the rest of the application
COPY . .

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

# Start the Rails server on port 3001
EXPOSE 3001
CMD ["bin/dev"]
