default: &default
  adapter: postgresql
  encoding: unicode

  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DATABASE_USER") { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'password' } %>
  pool: 5

development:
  <<: *default
  database: e_commerce_app_development

test:
  <<: *default
  database: e_commerce_app_test

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
