default: &default
  adapter: postgresql
  encoding: unicode

  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DATABASE_USER") { 'postgres' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'password' } %>
  pool: 5

development:
  <<: *default
  database: e_commerce_app_development

test:
  <<: *default
  database: e_commerce_app_test

production:
  <<: *default
  database: e_commerce_app_production
  username: e_commerce_app
  password: <%= ENV['E_COMMERCE_APP_DATABASE_PASSWORD'] %>
